name: Lint and Style

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff

      - name: Run linter
        run: ruff check --format=github .

      - name: Check code formatting
        run: black --check .
