name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Sublime package
        run: git archive --format=zip --output=Format.sublime-package HEAD

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Format.sublime-package
          draft: true
